diff --git a/Makefile b/Makefile
index 56682f8..d0b5c4c 100644
--- a/Makefile
+++ b/Makefile
@@ -6,15 +6,7 @@ ifeq ($(ui),)
   ui := ui-qt
 endif
 
-ifeq ($(profile),)
-  profile := compatibility
-  ifeq ($(out),)
-    out   := bsnes
-  endif
-else ifeq ($(out),)
-  out     := bsnes-$(profile)
-endif
-
+profile := accuracy
 objdir := obj/$(profile)
 
 # compiler
@@ -92,26 +84,13 @@ objects := $(patsubst %,$(objdir)/%.o,$(objects))
 
 # targets
 build: ui_build $(objects)
-ifeq ($(platform),osx)
-	@echo Linking $(osxbundle)...
-	@test -d $(osxbundle) || mkdir -p $(osxbundle)/Contents/MacOS
-	@$(strip $(cpp) -o $(osxbundle)/Contents/MacOS/$(out) $(objects) $(link))
-	@mkdir -p $(osxbundle)/Contents/Resources
-	@cp -f data/bsnes.icns $(osxbundle)/Contents/Resources/AppIcon.icns
-	@sed 's/@VERSION/v$(version)/g' data/Info.plist > $(osxbundle)/Contents/Info.plist
-else
 	@echo Linking out/$(out)...
 #	$(foreach qtdll,$(qtdlls),xcopy $(winqtpath)\bin\$(qtdll) .\out\ /D /Y &)
 #	$(foreach qtplatformdll,$(qtplatformdlls),xcopy $(winqtpath)\$(qtplatformdll) .\out\platforms\ /D /Y &)
-	@$(strip $(cpp) -o out/$(out) $(objects) $(link))
-endif
+	@$(strip $(cpp) -o bsnes $(objects) $(link))
 
 install: build plugins
 ifeq ($(platform),x)
-	install -D -m 755 out/$(out) $(DESTDIR)$(prefix)/bin/$(out)
-	install -D -m 644 data/bsnes.png $(DESTDIR)$(prefix)/share/pixmaps/bsnes.png
-	install -D -m 644 data/bsnes.desktop $(DESTDIR)$(prefix)/share/applications/bsnes.desktop
-	test -d ~/.bsnes || mkdir ~/.bsnes
 else ifeq ($(platform),osx)
 	mv -f $(osxbundle) /Applications/bsnes+.app
 	test -d ~/.bsnes || mkdir ~/.bsnes
@@ -131,10 +110,11 @@ else
 endif
 
 plugins: build
-	@$(MAKE) -C ../snesreader
-	@$(MAKE) -C ../snesfilter
-	@$(MAKE) -C ../snesmusic
-	@$(MAKE) -C ../supergameboy
+#	@$(MAKE) -C ../snesreader
+#	@$(MAKE) -C ../snesfilter
+#	@$(MAKE) -C ../snesmusic
+#	@$(MAKE) -C ../supergameboy
+	echo "Not building plugins for now"
 ifeq ($(platform),osx)
 	mkdir -p $(osxbundle)/Contents/Frameworks
 	cp -f ../snesreader/libsnesreader.dylib $(osxbundle)/Contents/Frameworks/libsnesreader.dylib
